name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write   # <-- required to push the output branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG from contributions
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pranjitbis
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
